In [1]:
import numpy as np
np.__version__

'1.24.2'

In [28]:
np.show_config()

openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['openblas\\lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BL

In [72]:
zeros=np.zeros((1,11))
zeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
zeros.nbytes

80

In [61]:
np.put(zeros,4,1)
zeros

array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [30]:
a=np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [35]:
b=np.flip(a,0)
b

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [38]:
matrix=np.arange(0,9)
matrix.shape=3,3
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
a=np.array([1,2,0,0,4,0])
a.nonzero()

(array([0, 1, 4], dtype=int64),)

In [43]:
b=np.ones(9)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [44]:
b.shape=3,3
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [45]:
tr=np.random.randint(1,100,(3,3,3))
tr

array([[[49, 55, 71],
        [63, 98, 87],
        [16, 84,  7]],

       [[39,  6, 72],
        [50, 21, 90],
        [44, 50, 90]],

       [[22, 53,  8],
        [58, 97,  9],
        [59, 33, 77]]])

In [46]:
tr=np.random.randint(1,100,(10,10))
print(tr)

[[42 88 60 88 87 40 95 59 52 46]
 [27 54 77 91 29 93 67 14 46 33]
 [77 71 94 10  2 28 45 10 23 17]
 [71 94 22 16 32 38  1 86  8 33]
 [48 23  9 54  2 35 24 90 72 14]
 [79 29 98 38 70 55 74 74 96 21]
 [95 46 86 62 29 90 72 34 90 76]
 [49 42 19 48  9 26 37 77  5 62]
 [30 59 81 44 68 61 71 14 20 67]
 [74 38 90 61 57 22 78 25 82 73]]


In [49]:
tr.max()

98

tr.min()

In [50]:
tr.min()

1

In [52]:
tr=np.random.randint(1,100,(1,30))
print(tr)
tr.mean()

[[67 95 80 57 45 69 64 81 72  9 96 44 44 74 32 32 53 66 63 42 87  5 89 41
   7 30 48 76 72 59]]


56.63333333333333

In [69]:
d=np.zeros((1,9))
d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [70]:
np.put(d,[0,8],[1,1])
d

array([[1., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [71]:
d.shape=3,3
d

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 1.]])

In [3]:
a = np.array([[0.0, 1.0], [-1.0, 0.0]])
print(a)

[[ 0.  1.]
 [-1.  0.]]


In [4]:
print(a + [0, 1])

[[ 0.  2.]
 [-1.  1.]]


In [6]:
print(a + np.array([[1, 2]]).T)

[[1. 2.]
 [1. 2.]]


In [12]:
c=np.zeros((5,5), dtype=np.int64)
c

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int64)

In [13]:
c[1:4, 1:4]=1
c

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]], dtype=int64)

In [14]:
y=np.arange(1,6)
a=np.arange(3,-2,-1)
rss=np.sum((y-a)**2)
rss

60

In [28]:
# some linear algebra functions
a = np.array([[0, 1], [2, 3]])

In [29]:
# determinant
np.linalg.det(a)

-2.0

In [30]:
# inverse matrix
a1=np.linalg.inv(a)
a1

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [33]:
a@a1

array([[1., 0.],
       [0., 1.]])

In [34]:
v = np.array([0, 1], dtype=np.float64)
a1@v

array([0.5, 0. ])

In [35]:
# solve system au=v
u = np.linalg.solve(a, v)
u

array([0.5, 0. ])

In [36]:
# eigenvalues l and eigenvectors u
l, u = np.linalg.eig(a)

In [37]:
l

array([-0.56155281,  3.56155281])

In [38]:
u

array([[-0.87192821, -0.27032301],
       [ 0.48963374, -0.96276969]])

In [6]:
# some random stuff
a=np.ones((5,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
a[1:-1,1:-1]=0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
# other option
a=np.ones((5,5))
b=np.pad(a,pad_width=1,mode='constant',constant_values=0)
b

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])