In [5]:
import numpy as np
import pandas as pd


In [3]:
data = {i: np.random.randint(10) for i in 'abcdefghij'}
s = pd.Series(data, index=list('facdxyz'))
s

f    4.0
a    8.0
c    0.0
d    8.0
x    NaN
y    NaN
z    NaN
dtype: float64

In [20]:
s=pd.Series(np.random.randint(0,9,5), index=list('abcde'))
s

a    7
b    4
c    3
d    6
e    2
dtype: int32

In [21]:
s.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [22]:
data = {i: np.random.randint(5) for i in 'abcde'}

In [23]:
data

{'a': 2, 'b': 1, 'c': 4, 'd': 2, 'e': 3}

In [24]:
s[s<s.std()]

e    2
dtype: int32

In [26]:
s[::3]

a    7
d    6
dtype: int32

In [27]:
s[[2,3]]

c    3
d    6
dtype: int32

In [28]:
np.diff(s)*5

array([-15,  -5,  15, -20])

In [29]:
s1=s
s1+s

a    14
b     8
c     6
d    12
e     4
dtype: int32

In [30]:
s1.rename('smth')
s1

a    7
b    4
c    3
d    6
e    2
dtype: int32

In [31]:
df = pd.DataFrame(np.random.randint(0, 10, (5, 3)),
                  columns=list('abc'))
df

a  b  c
0  7  5  9
1  8  7  9
2  5  4  1
3  2  4  0
4  3  0  9

In [32]:
df.assign(d=lambda x: x['a']*x['b'] + x['c'])

a  b  c   d
0  7  5  9  44
1  8  7  9  65
2  5  4  1  21
3  2  4  0   8
4  3  0  9   9

In [33]:
df.T

0  1  2  3  4
a  7  8  5  2  3
b  5  7  4  4  0
c  9  9  1  0  9

In [34]:
np.exp(df)

a            b            c
0  1096.633158   148.413159  8103.083928
1  2980.957987  1096.633158  8103.083928
2   148.413159    54.598150     2.718282
3     7.389056    54.598150     1.000000
4    20.085537     1.000000  8103.083928

In [35]:
df = pd.DataFrame(np.random.rand(5, 4),
                  index=pd.date_range('1/1/2020', periods=5),
                  columns=list('ABCD'))
df

A         B         C         D
2020-01-01  0.687939  0.454645  0.982107  0.488179
2020-01-02  0.047019  0.048544  0.480111  0.626344
2020-01-03  0.831651  0.869106  0.312332  0.762045
2020-01-04  0.760995  0.262755  0.622753  0.321543
2020-01-05  0.701540  0.961806  0.353805  0.561812

In [36]:
df.shape

(5, 4)

In [37]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [38]:
df.columns = ['col_' + str(i) for i in range(len(df.columns))]

df


col_0     col_1     col_2     col_3
2020-01-01  0.687939  0.454645  0.982107  0.488179
2020-01-02  0.047019  0.048544  0.480111  0.626344
2020-01-03  0.831651  0.869106  0.312332  0.762045
2020-01-04  0.760995  0.262755  0.622753  0.321543
2020-01-05  0.701540  0.961806  0.353805  0.561812

In [39]:
s.array

<PandasArray>
[7, 4, 3, 6, 2]
Length: 5, dtype: int32

In [40]:
s.index.array

<PandasArray>
['a', 'b', 'c', 'd', 'e']
Length: 5, dtype: object

In [41]:
np.asarray(s)

array([7, 4, 3, 6, 2])

In [42]:
s.to_numpy()

array([7, 4, 3, 6, 2])

In [4]:
s1 = pd.Series(np.arange(5),
               index=list('abcde'))
s2 = pd.Series(np.arange(5, 10),
               index=list('acexy'))
s1, s2


(a    0
 b    1
 c    2
 d    3
 e    4
 dtype: int32,
 a    5
 c    6
 e    7
 x    8
 y    9
 dtype: int32)

In [5]:
data = {'first_column': pd.Series(range(5), index=list('edcba')),
        'second_column': pd.Series(range(5, 10), index=list('gfedc')),
        'third_column': pd.Series(range(2, 7), index=list('acdfg'))}

# создаем датафрейм:
df = pd.DataFrame(data)
df

first_column  second_column  third_column
a           4.0            NaN           2.0
b           3.0            NaN           NaN
c           2.0            9.0           3.0
d           1.0            8.0           4.0
e           0.0            7.0           NaN
f           NaN            6.0           5.0
g           NaN            5.0           6.0

In [6]:
pd.DataFrame(data,
             # указываем нужные индексы:
             index=['c', 'd'])

first_column  second_column  third_column
c             2              9             3
d             1              8             4

In [7]:
pd.DataFrame(data,
             # указываем нужные индексы:
             index=['c', 'd', 'f', 'g', 'z'],
             # указываем необходимые столбцы:
             columns=['second_column',
                      'third_column',
                      'fourth_column'])


second_column  third_column fourth_column
c            9.0           3.0           NaN
d            8.0           4.0           NaN
f            6.0           5.0           NaN
g            5.0           6.0           NaN
z            NaN           NaN           NaN

In [9]:
data = np.array([('a', 11, .9),
                 ('b', 22, .8),
                 ('c', 33, 0.7)],
                dtype=[('col_1', 'U1'),
                       ('col_2', 'i2'),
                       ('col_3', 'f2')])
pd.DataFrame(data)

col_1  col_2     col_3
0     a     11  0.899902
1     b     22  0.799805
2     c     33  0.700195

In [10]:
pd.DataFrame(data, index=['one', 'two', 'three'])
pd.DataFrame(data,
             index=['one', 'two', 'three'],
             columns=['col_2', 'col_1', 'col_4'])

col_2 col_1 col_4
one       11     a   NaN
two       22     b   NaN
three     33     c   NaN

In [11]:
data = [{'a': 11, 'b': 22},
        {'b': 33, 'c': 44},
        {'a': 55, 'c': 66}]

pd.DataFrame(data,
             index=['one', 'two', 'three'],
             columns=['c', 'a', 'b'])


c     a     b
one     NaN  11.0  22.0
two    44.0   NaN  33.0
three  66.0  55.0   NaN

In [12]:
data = {'X': {'a': 1, 'b': 2},
        'Y': {'a': 11, 'c': 22}}

pd.DataFrame(data)


X     Y
a  1.0  11.0
b  2.0   NaN
c  NaN  22.0

In [13]:
data = {('group_1', 'x'):{('i', 'm'): 11, ('i', 'n'): 22,
                          ('j', 'm'): 11, ('j', 'n'): 22},
        ('group_1', 'y'):{('i', 'm'): 33, ('i', 'n'): 44,
                          ('j', 'm'): 33, ('j', 'n'): 44},
        ('group_1', 'z'):{('i', 'm'): 55, ('i', 'n'): 66,
                          ('j', 'm'): 55, ('j', 'n'): 66},
        ('group_2', 'x'):{('i', 'm'): 11, ('i', 'n'): 22,
                          ('j', 'm'): 11, ('j', 'n'): 22},
        ('group_2', 'y'):{('i', 'm'): 33, ('i', 'n'): 44,
                          ('j', 'm'): 33, ('j', 'n'): 44},
        ('group_2', 'z'):{('i', 'm'): 55, ('i', 'n'): 66,
                          ('j', 'm'): 55, ('j', 'n'): 66}}

pd.DataFrame(data)


group_1         group_2        
          x   y   z       x   y   z
i m      11  33  55      11  33  55
  n      22  44  66      22  44  66
j m      11  33  55      11  33  55
  n      22  44  66      22  44  66

In [14]:
df = pd.DataFrame(np.random.randint(0, 10, size=(5, 2)),
                  columns=['col_1', 'col_2'])
df


col_1  col_2
0      0      1
1      1      7
2      2      9
3      0      2
4      2      8

In [15]:
df['col_3'] = df['col_1']*100
df


col_1  col_2  col_3
0      0      1      0
1      1      7    100
2      2      9    200
3      0      2      0
4      2      8    200

In [16]:
df['col_5'] = 10
print(df)

   col_1  col_2  col_3  col_5
0      0      1      0     10
1      1      7    100     10
2      2      9    200     10
3      0      2      0     10
4      2      8    200     10


In [17]:
df['col_6'] = df['col_5'][::2]
df

col_1  col_2  col_3  col_5  col_6
0      0      1      0     10   10.0
1      1      7    100     10    NaN
2      2      9    200     10   10.0
3      0      2      0     10    NaN
4      2      8    200     10   10.0

In [18]:
df = pd.DataFrame(np.random.randint(0, 10, (5, 3)),
                  columns=list('abc'))

df

a  b  c
0  0  3  3
1  4  4  1
2  8  5  8
3  2  9  4
4  8  7  1

In [19]:
df.assign(d=lambda x: x['a']*x['b'] + x['c'])

a  b  c   d
0  0  3  3   3
1  4  4  1  17
2  8  5  8  48
3  2  9  4  22
4  8  7  1  57

In [20]:
df = pd.DataFrame(np.random.randint(0, 10, (5, 3)),
                  index=list('abcde'),
                  columns=list('XYZ'))
df

X  Y  Z
a  6  3  1
b  1  6  9
c  3  0  7
d  3  0  1
e  2  5  4

In [22]:
df.loc['c']

X    3
Y    0
Z    7
Name: c, dtype: int32

In [24]:
df.iloc[2]

X    3
Y    0
Z    7
Name: c, dtype: int32

In [25]:
df.iloc[2]['Y']

0

In [26]:
df.loc['b':'d']

X  Y  Z
b  1  6  9
c  3  0  7
d  3  0  1

In [27]:
df_1 = pd.DataFrame(np.arange(4*7).reshape(7, 4),
                    index=['row_'+str(i) for i in range(7)],
                    columns=['col_'+str(i) for i in range(4)])
df_1


col_0  col_1  col_2  col_3
row_0      0      1      2      3
row_1      4      5      6      7
row_2      8      9     10     11
row_3     12     13     14     15
row_4     16     17     18     19
row_5     20     21     22     23
row_6     24     25     26     27

In [28]:
df_2 = pd.DataFrame(np.arange(4*7). reshape(4, 7),
                    index=['row_'+str(i) for i in range(4)],
                    columns=['col_'+str(i) for i in range(7)])
df_2


col_0  col_1  col_2  col_3  col_4  col_5  col_6
row_0      0      1      2      3      4      5      6
row_1      7      8      9     10     11     12     13
row_2     14     15     16     17     18     19     20
row_3     21     22     23     24     25     26     27

In [29]:
df_1 * df_2

col_0  col_1  col_2  col_3  col_4  col_5  col_6
row_0    0.0    1.0    4.0    9.0    NaN    NaN    NaN
row_1   28.0   40.0   54.0   70.0    NaN    NaN    NaN
row_2  112.0  135.0  160.0  187.0    NaN    NaN    NaN
row_3  252.0  286.0  322.0  360.0    NaN    NaN    NaN
row_4    NaN    NaN    NaN    NaN    NaN    NaN    NaN
row_5    NaN    NaN    NaN    NaN    NaN    NaN    NaN
row_6    NaN    NaN    NaN    NaN    NaN    NaN    NaN

In [30]:
s = df_2.iloc[0]
s


col_0    0
col_1    1
col_2    2
col_3    3
col_4    4
col_5    5
col_6    6
Name: row_0, dtype: int32

In [31]:
df_2 * s

col_0  col_1  col_2  col_3  col_4  col_5  col_6
row_0      0      1      4      9     16     25     36
row_1      0      8     18     30     44     60     78
row_2      0     15     32     51     72     95    120
row_3      0     22     46     72    100    130    162

In [32]:
s = df_2.iloc[0][::2]
s


col_0    0
col_2    2
col_4    4
col_6    6
Name: row_0, dtype: int32

In [33]:
s = df_2['col_4']
s


row_0     4
row_1    11
row_2    18
row_3    25
Name: col_4, dtype: int32

In [34]:
df_2 - s

col_0  col_1  col_2  col_3  col_4  col_5  col_6  row_0  row_1  row_2  \
row_0    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
row_1    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
row_2    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
row_3    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   

       row_3  
row_0    NaN  
row_1    NaN  
row_2    NaN  
row_3    NaN

In [35]:
df_2.sub(s, axis=0)

col_0  col_1  col_2  col_3  col_4  col_5  col_6
row_0     -4     -3     -2     -1      0      1      2
row_1     -4     -3     -2     -1      0      1      2
row_2     -4     -3     -2     -1      0      1      2
row_3     -4     -3     -2     -1      0      1      2

In [36]:
2**df_2

col_0    col_1    col_2     col_3     col_4     col_5      col_6
row_0        1        2        4         8        16        32         64
row_1      128      256      512      1024      2048      4096       8192
row_2    16384    32768    65536    131072    262144    524288    1048576
row_3  2097152  4194304  8388608  16777216  33554432  67108864  134217728

In [37]:
df_1 = pd.DataFrame(np.random.randint(0, 3, (7, 4)),
                    index=['row_'+str(i) for i in range(7)],
                    columns=['col_'+str(i) for i in range(4)])
df_1

col_0  col_1  col_2  col_3
row_0      1      1      0      0
row_1      1      1      2      1
row_2      1      0      0      0
row_3      1      0      1      2
row_4      1      0      2      1
row_5      2      2      1      1
row_6      1      1      1      0

In [38]:
df_1 == df_1.loc['row_2']

col_0  col_1  col_2  col_3
row_0   True  False   True   True
row_1   True  False  False  False
row_2   True   True   True   True
row_3   True   True  False  False
row_4   True   True  False  False
row_5  False  False  False  False
row_6   True  False  False   True

In [39]:
df_2 = pd.DataFrame(np.random.randint(0, 3, (7, 4)),
                    index=['row_'+str(i) for i in range(7)],
                    columns=['col_'+str(i) for i in range(4)])
df_2


col_0  col_1  col_2  col_3
row_0      1      0      2      1
row_1      1      0      2      0
row_2      1      2      0      2
row_3      2      1      1      1
row_4      1      0      0      1
row_5      1      1      0      2
row_6      1      0      0      0

In [40]:
df_1 = pd.DataFrame(np.random.randint(0, 2, (7, 4)),
                    index=['row_'+str(i) for i in range(7)],
                    columns=['col_'+str(i) for i in range(4)],
                    # задаем логический тип данных:
                    dtype=bool)

df_2 = pd.DataFrame(np.random.randint(0, 2, (7, 4)),
                    index=['row_'+str(i) for i in range(7)],
                    columns=['col_'+str(i) for i in range(4)],
                    dtype=bool)
df_1 & df_2


col_0  col_1  col_2  col_3
row_0  False  False  False  False
row_1  False  False  False  False
row_2  False   True   True  False
row_3  False  False  False  False
row_4  False   True   True  False
row_5  False  False   True  False
row_6  False  False  False  False

In [41]:
df_1 = pd.DataFrame(np.arange(4*7).reshape(7, 4),
                    index=['row_'+str(i) for i in range(7)],
                    columns=['col_'+str(i) for i in range(4)])
df_1


col_0  col_1  col_2  col_3
row_0      0      1      2      3
row_1      4      5      6      7
row_2      8      9     10     11
row_3     12     13     14     15
row_4     16     17     18     19
row_5     20     21     22     23
row_6     24     25     26     27

In [42]:
np.exp2(df_1)

col_0       col_1       col_2        col_3
row_0         1.0         2.0         4.0          8.0
row_1        16.0        32.0        64.0        128.0
row_2       256.0       512.0      1024.0       2048.0
row_3      4096.0      8192.0     16384.0      32768.0
row_4     65536.0    131072.0    262144.0     524288.0
row_5   1048576.0   2097152.0   4194304.0    8388608.0
row_6  16777216.0  33554432.0  67108864.0  134217728.0

In [43]:
np.mean(df_1)

C:\Users\Иван\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\numpy\core\fromnumeric.py:3462: FutureWarning: In a future version, DataFrame.mean(axis=None) will return a scalar mean over the entire DataFrame. To retain the old behavior, use 'frame.mean(axis=0)' or just 'frame.mean()'
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)


col_0    12.0
col_1    13.0
col_2    14.0
col_3    15.0
dtype: float64

In [44]:
np.mean(np.arange(4*7).reshape(7, 4))

13.5

In [1]:
import seaborn as sns
data = sns.load_dataset('tips')
data

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [3]:
data.tail()

total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [6]:
df = pd.DataFrame(np.random.rand(5, 4),
                  index=pd.date_range('1/1/2020', periods=5),
                  columns=list('ABCD'))
df

A         B         C         D
2020-01-01  0.350838  0.239530  0.009480  0.734174
2020-01-02  0.629206  0.298992  0.509530  0.907284
2020-01-03  0.925036  0.610718  0.514707  0.108137
2020-01-04  0.876559  0.709479  0.968477  0.487610
2020-01-05  0.368414  0.239962  0.340912  0.328562

In [7]:
df.shape

(5, 4)

In [8]:
df.columns = ['col_' + str(i) for i in range(len(df.columns))]

df

col_0     col_1     col_2     col_3
2020-01-01  0.350838  0.239530  0.009480  0.734174
2020-01-02  0.629206  0.298992  0.509530  0.907284
2020-01-03  0.925036  0.610718  0.514707  0.108137
2020-01-04  0.876559  0.709479  0.968477  0.487610
2020-01-05  0.368414  0.239962  0.340912  0.328562

In [9]:
df.index = ['id_' + str(i) for i in range(len(df.index))]
df

col_0     col_1     col_2     col_3
id_0  0.350838  0.239530  0.009480  0.734174
id_1  0.629206  0.298992  0.509530  0.907284
id_2  0.925036  0.610718  0.514707  0.108137
id_3  0.876559  0.709479  0.968477  0.487610
id_4  0.368414  0.239962  0.340912  0.328562

In [11]:
s = pd.Series(np.random.rand(3000))
s.array

<PandasArray>
[  0.295858697850499, 0.44082331230826033, 0.15670495206553625,
 0.14056445982389754,  0.7905423625451116,  0.5223564131558519,
  0.3308334513137068,   0.611231026622326,  0.5283005256397104,
 0.30784496133930483,
 ...
  0.8887148582709545, 0.22109617198592157,  0.0476476315954254,
 0.21532538913167099,  0.6467805455681477, 0.30310589167086877,
  0.9226980679117026,  0.9613213686962866,  0.1780041685584809,
 0.48555765532937745]
Length: 3000, dtype: float64

In [12]:
s.index.array

<PandasArray>
[   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
 ...
 2990, 2991, 2992, 2993, 2994, 2995, 2996, 2997, 2998, 2999]
Length: 3000, dtype: int64

In [13]:
s.to_numpy()

array([0.2958587 , 0.44082331, 0.15670495, ..., 0.96132137, 0.17800417,
       0.48555766])

In [14]:
s_dt = pd.Series(pd.date_range('01/01/2020',
                               periods=5,
                               tz="Europe/Moscow"))
s_dt

0   2020-01-01 00:00:00+03:00
1   2020-01-02 00:00:00+03:00
2   2020-01-03 00:00:00+03:00
3   2020-01-04 00:00:00+03:00
4   2020-01-05 00:00:00+03:00
dtype: datetime64[ns, Europe/Moscow]

In [15]:
s_dt.to_numpy()

array([Timestamp('2020-01-01 00:00:00+0300', tz='Europe/Moscow'),
       Timestamp('2020-01-02 00:00:00+0300', tz='Europe/Moscow'),
       Timestamp('2020-01-03 00:00:00+0300', tz='Europe/Moscow'),
       Timestamp('2020-01-04 00:00:00+0300', tz='Europe/Moscow'),
       Timestamp('2020-01-05 00:00:00+0300', tz='Europe/Moscow')],
      dtype=object)

In [16]:
s_dt.to_numpy(dtype="datetime64[ns]")

array(['2019-12-31T21:00:00.000000000', '2020-01-01T21:00:00.000000000',
       '2020-01-02T21:00:00.000000000', '2020-01-03T21:00:00.000000000',
       '2020-01-04T21:00:00.000000000'], dtype='datetime64[ns]')

In [17]:
df.to_numpy()

array([[0.35083822, 0.23953022, 0.00947989, 0.73417361],
       [0.62920585, 0.298992  , 0.5095299 , 0.9072837 ],
       [0.92503584, 0.61071811, 0.51470728, 0.10813653],
       [0.87655949, 0.70947891, 0.9684769 , 0.48761046],
       [0.36841444, 0.2399621 , 0.34091237, 0.32856151]])

In [18]:
df['col_4'] = list('abcde')
df

col_0     col_1     col_2     col_3 col_4
id_0  0.350838  0.239530  0.009480  0.734174     a
id_1  0.629206  0.298992  0.509530  0.907284     b
id_2  0.925036  0.610718  0.514707  0.108137     c
id_3  0.876559  0.709479  0.968477  0.487610     d
id_4  0.368414  0.239962  0.340912  0.328562     e

In [19]:
df.to_numpy()

array([[0.3508382247955939, 0.23953021994541934, 0.00947988989034032,
        0.7341736082560301, 'a'],
       [0.6292058465256221, 0.2989919952714649, 0.5095299041145994,
        0.9072836957516579, 'b'],
       [0.9250358371592413, 0.6107181130869679, 0.5147072815364291,
        0.1081365326941377, 'c'],
       [0.8765594854384844, 0.7094789123472696, 0.9684768956434603,
        0.48761045879059006, 'd'],
       [0.36841443722109024, 0.23996209588161677, 0.34091236651009493,
        0.32856151298091707, 'e']], dtype=object)